---
name: PR Template.yml
about: 'pull request template '
title: "[PR]"
labels: ''
assignees: ''

---

---
name: pull request
about:  Use this template for pull request
title: "[DATE]: [FEATURE NAME]"
labels: bug, enhancement, customer-request, PR, tracking issue, needs triage
assignees: self
---
